apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: appsody-build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  outputs:
    resources:
      - name: docker-image
        type: image
  steps:
    - name: build
      securityContext:
        privileged: true
      image: appsody/appsody-buildah
      command: ['/bin/bash']
      args:
        - -c
        - "cd /workspace/$gitsource && appsody build --buildah --buildah-options='--tls-verify=false' -t $(outputs.resources.docker-image.url)"
      env:
        - name: gitsource
          value: git-source
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
